# =========================================================
# APPLICATION
# =========================================================
spring.application.name=student-registration-system
server.port=8080

# =========================================================
# DATASOURCE - MySQL
# =========================================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_registration_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# =========================================================
# THYMELEAF
# =========================================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# =========================================================
# FILE UPLOAD
# =========================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/student-photos

# =========================================================
# LOGGING
# =========================================================
logging.level.org.springframework=INFO
logging.level.com.enterprise.studentregistration=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n



# =========================================================
# EMAIL - Gmail SMTP
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=akshaydahiphale7778@gmail.com
app.mail.admin=akshaydahiphale7778@gmail.com





spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000